name: binary_app_tech_chat
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.2
  cloud_firestore: ^5.6.6
  get: ^4.7.2
  google_sign_in: ^6.3.0
  image_picker: ^1.1.2
  firebase_storage: ^12.4.5
  firebase_messaging: ^15.2.5
  flutter_local_notifications: ^19.0.0
  font_awesome_flutter: ^10.8.0
  flutter_launcher_icons: ^0.14.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/binaryapptech_logo.jpeg"
  min_sdk_android: 21

  web:
    generate: true
    image_path: "assets/binaryapptech_logo.jpeg"
    background_color: "#ffffff"
    theme_color: "#5e35b1"

  windows:
    generate: true
    image_path: "assets/binaryapptech_logo.jpeg"
    icon_size: 48

  macos:
    generate: true
    image_path: "assets/binaryapptech_logo.jpeg"


flutter:
  uses-material-design: true
  assets:
    - assets/
