// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDaq_GoI8FqSU76ibsfx1x-aWwW4s4cfIc',
    appId: '1:526926569689:web:4ba159dc7e154a311e1ec8',
    messagingSenderId: '526926569689',
    projectId: 'binary-app-tech-chat',
    authDomain: 'binary-app-tech-chat.firebaseapp.com',
    storageBucket: 'binary-app-tech-chat.firebasestorage.app',
    measurementId: 'G-9J6CQN24RJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAzJeYHIhgYBIpU2P7iK9sZs1X7KqJgt3I',
    appId: '1:526926569689:android:7bb6dec2a1ee8e571e1ec8',
    messagingSenderId: '526926569689',
    projectId: 'binary-app-tech-chat',
    storageBucket: 'binary-app-tech-chat.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCCxHkCD0wfu9MhDLy_rtDwHsaE_tlzwFM',
    appId: '1:526926569689:ios:0e25e96519a381721e1ec8',
    messagingSenderId: '526926569689',
    projectId: 'binary-app-tech-chat',
    storageBucket: 'binary-app-tech-chat.firebasestorage.app',
    iosBundleId: 'com.example.binaryAppTechChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCCxHkCD0wfu9MhDLy_rtDwHsaE_tlzwFM',
    appId: '1:526926569689:ios:0e25e96519a381721e1ec8',
    messagingSenderId: '526926569689',
    projectId: 'binary-app-tech-chat',
    storageBucket: 'binary-app-tech-chat.firebasestorage.app',
    iosBundleId: 'com.example.binaryAppTechChat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDaq_GoI8FqSU76ibsfx1x-aWwW4s4cfIc',
    appId: '1:526926569689:web:d147007a5cbc3b331e1ec8',
    messagingSenderId: '526926569689',
    projectId: 'binary-app-tech-chat',
    authDomain: 'binary-app-tech-chat.firebaseapp.com',
    storageBucket: 'binary-app-tech-chat.firebasestorage.app',
    measurementId: 'G-1LXHC7515N',
  );
}
